(in-package #:ember-forge)

(defun save-slot-dirname (slot)
  (format nil "slot~D" (%normalize-save-slot slot)))

(defun save-slot-dir (slot)
  (merge-pathnames
   (make-pathname :directory `(:relative ,(save-slot-dirname slot)))
   (saves-dir)))

(defun save-slot-file ()
  "save.lisp")

(defun legacy-save-slot-filename (slot)
  (let ((n (%normalize-save-slot slot)))
    (if (= n 1)
        "save.lisp"
        (format nil "save~D.lisp" n))))

(defun saves-dir ()
  "Local-only saves directory under the current working directory."
  (merge-pathnames
   (make-pathname :directory '(:relative "saves"))
   (uiop:getcwd)))

(defun legacy-save-path (state &key slot)
  (let* ((sl (or slot (and state (game-state-save-slot state)) 1)))
    (merge-pathnames (legacy-save-slot-filename sl) (saves-dir))))

(defun save-path (state &key slot)
  (let* ((sl (or slot (and state (game-state-save-slot state)) 1)))
    (merge-pathnames (save-slot-file) (save-slot-dir sl))))

(defun migrate-legacy-save! (state &key slot)
  (let* ((sl (or slot (and state (game-state-save-slot state)) 1))
         (legacy (legacy-save-path state :slot sl))
         (path (save-path state :slot sl)))
    (when (and (probe-file legacy)
               (not (probe-file path)))
      (ensure-directories-exist path)
      (handler-case
          (rename-file legacy path)
        (error ()
          (ignore-errors (uiop:copy-file legacy path))
          (ignore-errors (delete-file legacy))))
      t)))

(defun %hash-to-alist (ht)
  (let ((out '()))
    (maphash (lambda (k v) (push (cons k v) out)) ht)
    (nreverse out)))

(defun %alist-to-hash (alist &key (test 'eq))
  (let ((ht (make-hash-table :test test)))
    (dolist (cell alist ht)
      (setf (gethash (car cell) ht) (cdr cell)))))

(defun state-to-plist (state)
  (list
   :version 3
   :saved-at (get-universal-time)
   :tick (game-state-tick state)
   :resources (%hash-to-alist (game-state-resources state))
   :caps (%hash-to-alist (game-state-caps state))
   :ever-produced (%hash-to-alist (game-state-ever-produced state))
   :unlocked (copy-list (game-state-unlocked state))
   :production (%hash-to-alist (game-state-production state))
   :buildings (loop for id being the hash-keys of (game-state-buildings state)
                    using (hash-value inst)
                    collect (list id
                                  (building-instance-count inst)
                                  (building-instance-level inst)))
   :building-mults (%hash-to-alist (game-state-building-mults state))
   :discovered (copy-list (game-state-discovered state))
   :smelt-queue (mapcar (lambda (job)
                          (list (smelt-job-recipe job)
                                (smelt-job-progress job)
                                (smelt-job-duration job)
                                (smelt-job-source job)))
                        (game-state-smelt-queue state))
   :upgrades (copy-list (game-state-upgrades state))
   :eternal-upgrades (copy-list (game-state-eternal-upgrades state))
   :achievements (copy-list (game-state-achievements state))
   :sell-mult (game-state-sell-mult state)
   :shop-discount (game-state-shop-discount state)
   :shop-purchases (%hash-to-alist (game-state-shop-purchases state))
   :essence (game-state-essence state)
   :ascensions (game-state-ascensions state)
   :prod-mult (game-state-prod-mult state)
   :click-mult (game-state-click-mult state)
   :gather-mult (game-state-gather-mult state)
   :smelt-speed-mult (game-state-smelt-speed-mult state)
   :manual-mine-duration (game-state-manual-mine-duration state)
   :manual-gather-duration (game-state-manual-gather-duration state)
   :event-timer (game-state-event-timer state)
   :smelt-boost-timer (game-state-smelt-boost-timer state)
   :iron-penalty-timer (game-state-iron-penalty-timer state)
   :active-panel (game-state-active-panel state)
   :smelt-slots-extra (game-state-smelt-slots-extra state)))

(defun plist-to-state! (state pl)
  (labels ((g (k &optional default) (getf pl k default)))
    (setf (game-state-tick state) (g :tick 0))
    (setf (game-state-resources state) (%alist-to-hash (g :resources '())))
    (setf (game-state-caps state) (%alist-to-hash (g :caps '())))
    (setf (game-state-ever-produced state) (%alist-to-hash (g :ever-produced '())))
    (setf (game-state-unlocked state) (g :unlocked (list :stone :coal :coins)))
    (setf (game-state-production state) (%alist-to-hash (g :production '())))
    (setf (game-state-buildings state)
          (let ((ht (make-hash-table :test 'eq)))
            (dolist (row (g :buildings '()) ht)
              (destructuring-bind (id count level) row
                (setf (gethash id ht)
                      (make-building-instance :id id :count count :level level))))))
    (setf (game-state-building-mults state) (%alist-to-hash (g :building-mults '())))
    (setf (game-state-discovered state) (g :discovered '()))
    (setf (game-state-smelt-queue state)
          (mapcar (lambda (row)
                    (destructuring-bind (recipe progress duration source) row
                      (make-smelt-job :recipe recipe
                                      :progress (coerce progress 'single-float)
                                      :duration (coerce duration 'single-float)
                                      :source (or source :manual))))
                  (g :smelt-queue '())))
    (setf (game-state-upgrades state) (g :upgrades '()))
    (setf (game-state-eternal-upgrades state) (g :eternal-upgrades '()))
    (setf (game-state-achievements state) (g :achievements '()))
    (setf (game-state-sell-mult state) (coerce (g :sell-mult 1.0d0) 'double-float))
    (setf (game-state-shop-discount state) (coerce (g :shop-discount 1.0d0) 'double-float))
    (setf (game-state-shop-purchases state) (%alist-to-hash (g :shop-purchases '())))
    (setf (game-state-essence state) (coerce (g :essence 0.0d0) 'double-float))
    (setf (game-state-ascensions state) (g :ascensions 0))
    (setf (game-state-prod-mult state) (coerce (g :prod-mult 1.0d0) 'double-float))
    (setf (game-state-click-mult state) (coerce (g :click-mult 1.0d0) 'double-float))
    (setf (game-state-gather-mult state) (coerce (g :gather-mult 1.0d0) 'double-float))
    (setf (game-state-smelt-speed-mult state) (coerce (g :smelt-speed-mult 1.0d0) 'double-float))
    (setf (game-state-manual-mine-duration state) (coerce (g :manual-mine-duration 3.0) 'single-float))
    (setf (game-state-manual-gather-duration state) (coerce (g :manual-gather-duration 3.0) 'single-float))
    (setf (game-state-event-timer state) (coerce (g :event-timer 90.0) 'single-float))
    (setf (game-state-active-event state) nil)
    (setf (game-state-smelt-boost-timer state) (coerce (g :smelt-boost-timer 0.0) 'single-float))
    (setf (game-state-iron-penalty-timer state) (coerce (g :iron-penalty-timer 0.0) 'single-float))
    (setf (game-state-active-panel state) (g :active-panel :forge))
    (setf (game-state-smelt-slots-extra state) (g :smelt-slots-extra 0))
    state))

(defun save-game (state)
  (labels ((try (path)
             (ensure-directories-exist path)
             (with-open-file (f path :direction :output :if-exists :supersede)
               (prin1 (state-to-plist state) f))
             path))
    (handler-case
        (try (save-path state))
      (error ()
        nil))))

(defun load-save (state)
  (labels ((try (path)
             (when (probe-file path)
               (with-open-file (f path)
                 (let ((pl (read f nil nil)))
                   (when pl
                     (plist-to-state! state pl)
                     (setf (game-state-last-save-ut state) (getf pl :saved-at 0))
                     t))))))
    (or (try (save-path state))
        (let ((sl (and state (game-state-save-slot state))))
          (when (try (legacy-save-path state :slot sl))
            (ignore-errors (migrate-legacy-save! state :slot sl))
            t))
        nil)))

(defun save-exists-p (state &key slot)
  (let* ((sl (or slot (and state (game-state-save-slot state)) 1))
         (path (save-path state :slot sl))
         (legacy (legacy-save-path state :slot sl)))
    (or (not (null (probe-file path)))
        (not (null (probe-file legacy))))))

(defun delete-save (state &key slot)
  (let* ((sl (or slot (and state (game-state-save-slot state)) 1))
         (path (save-path state :slot sl))
         (dir (save-slot-dir sl))
         (legacy (legacy-save-path state :slot sl))
         (deleted nil))
    (when (or (probe-file path) (probe-file dir))
      (ignore-errors (uiop:delete-directory-tree dir :validate t))
      (setf deleted t))
    (when (and (not deleted) (probe-file legacy))
      (ignore-errors (delete-file legacy))
      (setf deleted t))
    deleted))
