(in-package #:ember-forge)

(defun render-panel-upgrades (ren state font font-lg x y w h)
  (draw-panel-background ren :upgrades x y w h)
  (draw-label ren font-lg "UPGRADES" (+ x 20) (+ y 10) :text)

  (let* ((row-h 44)
         (u-x (+ x 24))
         (u-y (+ y 56))
         (u-w (- w 48))
         (col-gap 16)
         (col-w (max 0 (floor (/ (- u-w col-gap) 2))))
         (items (loop for def in *upgrades*
                      when (or (upgrade-owned-p state (upgrade-def-id def))
                               (upgrade-available-p state def))
                        collect def)))
    (loop for def in items
          for idx from 0
          for col = (mod idx 2)
          for row = (floor idx 2)
          for col-x = (+ u-x (* col (+ col-w col-gap)))
          for row-y = (+ u-y (* row (+ row-h 8)))
          while (< (+ row-y row-h) (+ y h -8))
          do (let* ((id (upgrade-def-id def))
                    (owned (upgrade-owned-p state id))
                    (cost (upgrade-def-cost def))
                    (can-buy (and (not owned) (can-afford-plist-p state cost)))
                    (btn-w 84)
                    (btn-h (- row-h 16))
                    (btn-x (+ col-x (- col-w btn-w 8)))
                    (btn-y (+ row-y 8))
                    (text-x (+ col-x 10))
                    (text-right (- btn-x 10))
                    (text-w (max 0 (- text-right text-x)))
                    (cost-w (min 220 text-w))
                    (desc-w (max 0 (- text-w cost-w 10)))
                    (name-full (format nil "~A~A" (if owned "✓ " "") (upgrade-def-name def)))
                    (desc-full (upgrade-def-description def))
                    (cost-full (%fmt-cost cost))
                    (name-fit (fit-text-to-width font name-full text-w))
                    (desc-fit (fit-text-to-width font desc-full desc-w))
                    (cost-fit (fit-text-to-width font cost-full cost-w))
                    (truncated (or (not (string= name-fit name-full))
                                   (not (string= desc-fit desc-full))))
                    (hovered (rect-hovered-p col-x row-y col-w row-h)))
               (draw-rect ren col-x row-y col-w row-h :bg-sidebar :border-color :btn-hover)
               (draw-label ren font name-fit text-x (+ row-y 6) (if owned :text-dim :text))
               (draw-label ren font desc-fit text-x (+ row-y 24) :text-dim)
               (draw-label ren font cost-fit text-right (+ row-y 24) :text-dim :align :right)
               (when (and hovered truncated)
                 (ui-set-tooltip (format nil "~A~%~A" (upgrade-def-name def) desc-full)
                                 :x (+ col-x 8)
                                 :y row-y
                                 :placement :above))
               (when (draw-button ren font (if owned "Owned" "Buy")
                                  btn-x btn-y btn-w btn-h
                                  :enabled can-buy)
                 (buy-upgrade! state id)))))
  state)
