(in-package #:ember-forge)

(defun render-panel-prestige (ren state font font-lg x y w h)
  (draw-panel-background ren :prestige x y w h)
  (draw-label ren font-lg "PRESTIGE" (+ x 20) (+ y 10) :text)

  (draw-label ren font (format nil "Ascensions: ~D" (game-state-ascensions state))
              (+ x 24) (+ y 64) :text)
  (draw-label ren font (format nil "Ember Essence: ~A" (fmt-number (game-state-essence state)))
              (+ x 24) (+ y 88) :text)
  (draw-label ren font (format nil "Ember produced: ~A" (fmt-number (resource-ever state :ember)))
              (+ x 24) (+ y 112) :text-dim)

  (let ((can (prestige-available-p state)))
    (draw-label ren font
                (if can
                    (format nil "Gain ~D Essence and reset (formula: floor(sqrt(ember)) + asc*2)." (essence-gain state))
                    "Prestige unlocks after producing 1 Ember Crystal.")
                (+ x 24) (+ y 140) :text-dim)
    (when (draw-button ren font (if can (format nil "ASCEND (+~D)" (essence-gain state)) "ASCEND")
                       (+ x 24) (+ y 190) 220 44
                       :enabled can)
      (ascend! state)))

  (let* ((total (length *achievements*))
         (got (length (game-state-achievements state)))
         (ax (+ x 24))
         (ay (+ y 260)))
    (draw-label ren font (format nil "Achievements: ~D/~D" got total) ax ay :text)
    (let ((yy (+ ay 22))
          (shown 0))
      (dolist (id (reverse (game-state-achievements state)))
        (when (< shown 8)
          (let ((def (find id *achievements* :key #'achievement-def-id :test #'eq)))
            (draw-label ren font
                        (if def (format nil "✓ ~A" (achievement-def-name def)) (format nil "✓ ~A" id))
                        (+ ax 16) (+ yy (* shown 18)) :text-dim)
            (incf shown))))))

  (let* ((u-x (+ x 420))
         (u-y (+ y 64))
         (u-w (- w 444))
         (row-h 52)
         (i 0))
    (draw-label ren font "ETERNAL UPGRADES" u-x (- u-y 18) :text)
    (dolist (def *eternal-upgrades*)
      (let* ((id (eternal-upgrade-def-id def))
             (owned (eternal-upgrade-owned-p state id))
             (cost (eternal-upgrade-def-cost def))
             (can-buy (and (not owned) (>= (game-state-essence state) cost)))
             (row-y (+ u-y (* i (+ row-h 8))))
             (btn-x (+ u-x (- u-w 92)))
             (btn-y (+ row-y 10))
             (btn-w 84)
             (btn-h (- row-h 20))
             (cost-right (- btn-x 12)))
        (incf i)
        (draw-rect ren u-x row-y u-w row-h :bg-sidebar :border-color :btn-hover)
        (draw-label ren font
                    (format nil "~A~A" (if owned "✓ " "") (eternal-upgrade-def-name def))
                    (+ u-x 10) (+ row-y 6) (if owned :text-dim :text))
        (draw-label ren font (eternal-upgrade-def-description def) (+ u-x 10) (+ row-y 26) :text-dim)
        (draw-label ren font (format nil "Cost: ~A" (fmt-number cost))
                    cost-right (+ row-y 6) :text-dim :align :right)
        (when (draw-button ren font (if owned "Owned" "Buy")
                           btn-x btn-y btn-w btn-h
                           :enabled can-buy)
          (buy-eternal-upgrade! state id)))))
  state)
