(in-package #:ember-forge)

(defun render-resource-sidebar (ren state font x y w h)
  (draw-rect ren x y w h :bg-sidebar :border-color :btn-hover)
  (draw-label ren font "RESOURCES" (+ x 14) (+ y 10) :text)
  (let* ((rows (sort (copy-list (game-state-unlocked state))
                     (lambda (a b)
                       (let ((ta (resource-tier a))
                             (tb (resource-tier b)))
                         (if (= ta tb)
                             (string< (resource-name a) (resource-name b))
                             (< ta tb))))))
         (row-h 26)
         (y0 (+ y 36)))
    (loop for res in rows
          for i from 0
          for yy = (+ y0 (* i (+ row-h 4)))
          while (< (+ yy row-h) (+ y h -8))
          for amt = (resource-amount state res)
          for cap = (resource-cap state res)
          for rate = (gethash res (game-state-production state) 0.0d0)
          do (draw-resource-icon ren res (+ x 14) (+ yy 7))
             (draw-label ren font (resource-name res) (+ x 32) (+ yy 4) :text)
             (draw-label ren font (fmt-number amt) (+ x 160) (+ yy 4) :text-dim)
             (draw-label ren font (format nil "/~A" (fmt-number cap)) (+ x 220) (+ yy 4) :text-dim)
             (when (/= rate 0.0d0)
               (draw-label ren font (fmt-rate rate) (+ x 32) (+ yy 18) :text-dim)))))

(defun render-top-bar (ren state font)
  (draw-rect ren 0 0 +window-width+ 32 :bg-top :border-color :btn-hover)
  (draw-label ren font "Ember Forge" 12 7 :text)
  (draw-label ren font (format nil "Coins: ~A" (fmt-number (resource-amount state :coins))) 220 7 :gold)
  (draw-label ren font (format nil "Stone: ~A" (fmt-number (resource-amount state :stone))) 400 7 :text-dim)
  (draw-label ren font (format nil "Coal: ~A" (fmt-number (resource-amount state :coal))) 560 7 :text-dim)
  (draw-label ren font (format nil "FPS: ~D" (game-state-fps state)) (- +window-width+ 80) 7 :text-dim))

(defun render-nav-tabs (ren state font)
  (draw-rect ren 0 32 +window-width+ 32 :bg-panel :border-color :btn-hover)
  (let* ((tabs (list (cons :forge "Forge")
                     (cons :mine "Mine")
                     (cons :upgrades "Upgrades")
                     (cons :recipes "Recipes")
                     (cons :shop "Shop")
                     (cons :prestige "Prestige")))
         (x 12)
         (y 36))
    (dolist (tab tabs)
      (let* ((id (car tab))
             (label (cdr tab))
             (active (eq (game-state-active-panel state) id))
             (w 120))
        (when (draw-button ren font label x y w 24
                           :enabled t
                           :color (if active :btn-active :btn-normal))
          (setf (game-state-active-panel state) id))
        (incf x (+ w 8))))))

(defun render-main-panel (ren state font font-lg x y w h)
  (ecase (game-state-active-panel state)
    (:forge (render-panel-forge ren state font font-lg x y w h))
    (:mine (render-panel-mine ren state font font-lg x y w h))
    (:upgrades (render-panel-upgrades ren state font font-lg x y w h))
    (:recipes (render-panel-recipes ren state font font-lg x y w h))
    (:shop (render-panel-shop ren state font font-lg x y w h))
    (:prestige (render-panel-prestige ren state font font-lg x y w h))))

(defun render-event-overlay (ren state font font-lg)
  (let* ((id (game-state-active-event state))
         (ev (and id (find-event-def id))))
    (when ev
      (draw-rect ren 0 0 +window-width+ +window-height+ '(0 0 0 180))
      (let* ((pw 760)
             (ph 420)
             (px (floor (/ (- +window-width+ pw) 2)))
             (py (floor (/ (- +window-height+ ph) 2))))
        (draw-rect ren px py pw ph :bg-panel :border-color :btn-active)
        (draw-label ren font-lg (event-def-name ev) (+ px 24) (+ py 18) :text)
        (draw-multiline-label ren font (event-def-text ev) (+ px 24) (+ py 64) :text-dim
                              :line-height 18)
        (let* ((choices (event-def-choices ev))
               (btn-x (+ px 24))
               (btn-w (- pw 48))
               (btn-h 34)
               (btn-y (+ py 200)))
          (loop for choice in choices
                for i from 0
                for yy = (+ btn-y (* i (+ btn-h 10)))
                for label = (event-choice-label choice)
                for can = (event-choice-can choice)
                for enabled = (if can (funcall can state) t)
                do (when (draw-button ren font label btn-x yy btn-w btn-h
                                      :enabled enabled
                                      :tooltip (if enabled nil "Insufficient resources."))
                     (choose-active-event! state i)))))
      t)))

(defun render-frame (ren state font font-lg)
  (set-render-color* ren :bg)
  (sdl2:render-clear ren)

  (ecase (game-state-screen state)
    (:menu
     (let ((*ui-input-blocked* nil))
       (render-main-menu ren state font font-lg)
       (render-notifications ren font state 0 (- +window-height+ 28) +window-width+ 28)
       (render-tooltip ren font)))
    (:options
     (let ((*ui-input-blocked* nil))
       (render-options-menu ren state font font-lg)
       (render-notifications ren font state 0 (- +window-height+ 28) +window-width+ 28)
       (render-tooltip ren font)))
    (:game
     (let* ((modal (game-state-active-event state))
            (main-x 0)
            (main-y 64)
            (sidebar-w 280)
            (main-w (- +window-width+ sidebar-w))
            (main-h (- +window-height+ 64 28))
            (sidebar-x main-w)
            (sidebar-y 64)
            (sidebar-h main-h))
       (render-top-bar ren state font)
       (let ((*ui-input-blocked* (not (null modal))))
         (render-nav-tabs ren state font)
         (render-main-panel ren state font font-lg main-x main-y main-w main-h)
         (render-resource-sidebar ren state font sidebar-x sidebar-y sidebar-w sidebar-h)
         (render-notifications ren font state 0 (- +window-height+ 28) +window-width+ 28))

       (when modal
         (let ((*ui-input-blocked* nil))
           (render-event-overlay ren state font font-lg)))

       (render-tooltip ren font))))

  (sdl2:render-present ren))
