(in-package #:ember-forge)

(defun %measure-line (font text)
  (let ((surface (sdl2-ttf:render-utf8-blended font (or text "") 255 255 255 255)))
    (unwind-protect
        (values (sdl2:surface-width surface) (sdl2:surface-height surface))
      (autowrap:autocollect-cancel surface)
      (sdl2:free-surface surface))))

(defun render-tooltip (ren font)
  (when (and *ui-tooltip-text* (plusp (length *ui-tooltip-text*)))
    (let* ((lines (ui-split-lines *ui-tooltip-text*))
           (max-w 0)
           (max-h 0))
      (dolist (line lines)
        (multiple-value-bind (w h) (%measure-line font line)
          (setf max-w (max max-w w))
          (setf max-h (max max-h h))))
      (let* ((padding 8)
             (line-h (max 14 (+ max-h 2)))
             (box-w (+ max-w (* 2 padding)))
             (box-h (+ (* (length lines) line-h) (* 2 padding)))
             (anchor-x (or *ui-tooltip-x* *ui-mouse-x*))
             (anchor-y (or *ui-tooltip-y* *ui-mouse-y*))
             (x 0)
             (y 0))
        (ecase (or *ui-tooltip-placement* :mouse)
          (:mouse
           (setf x (+ anchor-x 16)
                 y (+ anchor-y 16))
           (when (> (+ x box-w) +window-width+)
             (setf x (max 0 (- anchor-x box-w 16))))
           (when (> (+ y box-h) +window-height+)
             (setf y (max 0 (- anchor-y box-h 16)))))
          (:above
           (setf x anchor-x
                 y (- anchor-y box-h 12))
           (when (< y 0)
             (setf y (+ anchor-y 16)))
           (when (> (+ x box-w) +window-width+)
             (setf x (max 0 (- +window-width+ box-w))))
           (when (> (+ y box-h) +window-height+)
             (setf y (max 0 (- +window-height+ box-h))))))
        (draw-rect ren x y box-w box-h '(0 0 0 220) :border-color :btn-hover)
        (draw-multiline-label ren font *ui-tooltip-text*
                              (+ x padding) (+ y padding) :text
                              :line-height line-h)))))
