(in-package #:ember-forge)

(defun update-fps! (state dt)
  (incf (game-state-frame-counter state))
  (incf (game-state-frame-accum state) (coerce dt 'single-float))
  (when (>= (game-state-frame-accum state) 1.0)
    (setf (game-state-fps state) (game-state-frame-counter state))
    (setf (game-state-frame-counter state) 0)
    (decf (game-state-frame-accum state) 1.0))
  state)

(defun tick-game (state dt)
  (incf (game-state-tick state))
  (tick-manual-jobs! state dt)
  (tick-buildings state dt)
  (tick-auto-furnaces! state)
  (tick-smelt-queue! state dt)
  (tick-events! state dt)
  (tick-notifications! state dt)
  (when (zerop (mod (game-state-tick state) 30))
    (maybe-unlock-produced-resources! state))
  (when (zerop (mod (game-state-tick state) 60))
    (maybe-unlock-achievements! state))
  (update-fps! state dt)
  state)

(defun maybe-autosave (state)
  (when (game-state-autosave-enabled state)
    (let* ((now (get-universal-time))
           (interval (max 10 (game-state-autosave-interval state))))
      (when (or (= (game-state-last-save-ut state) 0)
                (>= (- now (game-state-last-save-ut state)) interval))
        (save-game state)
        (setf (game-state-last-save-ut state) now)))))

(defun handle-keydown (state keysym)
  (let ((sc (sdl2:scancode-value keysym)))
    (cond
      ((sdl2:scancode= sc :scancode-f11)
       (setf (game-state-fullscreen-enabled state)
             (not (game-state-fullscreen-enabled state)))
       (ignore-errors (save-options state))
       (add-notification! state
                          (format nil "Fullscreen: ~A"
                                  (if (game-state-fullscreen-enabled state) "On" "Off"))
                          :color :text-dim)
       t)
      ((game-state-active-event state)
       nil)
      ((eq (game-state-screen state) :game)
       (cond
         ((sdl2:scancode= sc :scancode-1) (setf (game-state-active-panel state) :forge))
         ((sdl2:scancode= sc :scancode-2) (setf (game-state-active-panel state) :mine))
         ((sdl2:scancode= sc :scancode-3) (setf (game-state-active-panel state) :upgrades))
         ((sdl2:scancode= sc :scancode-4) (setf (game-state-active-panel state) :recipes))
         ((sdl2:scancode= sc :scancode-5) (setf (game-state-active-panel state) :shop))
         ((sdl2:scancode= sc :scancode-6) (setf (game-state-active-panel state) :prestige))
         ((sdl2:scancode= sc :scancode-escape) (setf (game-state-screen state) :menu))))
      ((eq (game-state-screen state) :options)
       (cond
         ((sdl2:scancode= sc :scancode-escape)
          (ignore-errors (save-options state))
          (setf (game-state-screen state) :menu))
         (t nil)))
      (t
       (cond
         ((sdl2:scancode= sc :scancode-escape)
          (if (game-state-game-started-p state)
              (setf (game-state-screen state) :game)
              (sdl2:push-event :quit)))
         ((sdl2:scancode= sc :scancode-return)
          (cond
            ((game-state-game-started-p state) (setf (game-state-screen state) :game))
            ((save-exists-p state) (start-continue-game! state))))
         (t nil))))))

(defun %find-font (relative)
  (or (probe-file relative)
      (probe-file (merge-pathnames relative (uiop:getcwd)))
      (ignore-errors (probe-file (asdf:system-relative-pathname :ember-forge relative)))))

(defun run-game ()
  (sdl2:with-init (:video :timer)
    (sdl2-ttf:init)
    (sdl2-image:init '(:png))
    (sdl2:with-window (win :title "Ember Forge"
                           :w +window-width+ :h +window-height+
                           :flags '(:shown :resizable))
      (sdl2:with-renderer (ren win :flags '(:accelerated :presentvsync))
        (sdl2:set-render-draw-blend-mode ren :blend)
        (ignore-errors
         (sdl2-ffi.functions:sdl-render-set-logical-size ren +window-width+ +window-height+))
        (let* ((state (make-initial-state))
               (mouse-win-x 0)
               (mouse-win-y 0)
               (clicked nil)
               (prev-left-down nil)
               (font nil)
               (font-lg nil)
               (loaded-font-choice "")
               (fullscreen-applied nil))
	          (load-options! state)
	          (setf fullscreen-applied (not (null (game-state-fullscreen-enabled state))))
	          (ignore-errors
	           (sdl2:set-window-fullscreen win (if fullscreen-applied :desktop nil)))
	          (ignore-errors
	           (sdl2-ffi.functions:sdl-render-set-logical-size ren +window-width+ +window-height+))
	          (scan-fonts!)
	          (labels ((try-open-font (path size)
	                     (ignore-errors
	                      (sdl2-ttf:open-font path size)))
                   (open-font-choice (choice)
                     (let* ((file (resolve-font-file choice))
                            (path (and file (namestring file)))
                            (f (and path (try-open-font path 14)))
                            (flg (and path (try-open-font path 20))))
                       (cond
                         ((and f flg)
                          (when font (ignore-errors (sdl2-ttf:close-font font)))
                          (when font-lg (ignore-errors (sdl2-ttf:close-font font-lg)))
                          (setf font f
                                font-lg flg
                                loaded-font-choice choice)
                          (add-notification! state (format nil "Font: ~A" (font-display-name choice))
                                             :color :text-dim)
                          t)
                         (t
                          (when f (ignore-errors (sdl2-ttf:close-font f)))
                          (when flg (ignore-errors (sdl2-ttf:close-font flg)))
                          nil))))
                   (ensure-fonts-loaded ()
                     (let* ((choice (game-state-font-path state)))
                       (or (and (stringp choice) (plusp (length choice)) (open-font-choice choice))
                           (let ((fallback (default-font-choice)))
                             (setf (game-state-font-path state) fallback)
                             (open-font-choice fallback))
                           (let ((fallback2 (or (%find-font "assets/fonts/JetBrainsMono/fonts/ttf/JetBrainsMono-Regular.ttf")
                                                (%find-font "fonts/JetBrainsMono/fonts/ttf/JetBrainsMono-Regular.ttf"))))
                             (when fallback2
                               (let ((f (try-open-font (namestring fallback2) 14))
                                     (flg (try-open-font (namestring fallback2) 20)))
                                 (when (and f flg)
                                   (let ((choice2 (namestring fallback2)))
                                     (setf (game-state-font-path state) choice2
                                           font f
                                           font-lg flg
                                           loaded-font-choice choice2))
                                   t)))))))
                   (maybe-reload-fonts ()
                     (let ((choice (game-state-font-path state)))
                       (when (and (stringp choice)
                                  (plusp (length choice))
                                  (not (string= choice loaded-font-choice)))
	                         (unless (open-font-choice choice)
	                           (setf (game-state-font-path state) loaded-font-choice)
	                           (add-notification! state "Failed to load font." :color :rust)))))
                   (apply-fullscreen (enabled)
                     (ignore-errors
                      (sdl2:set-window-fullscreen win (if enabled :desktop nil)))
                     (ignore-errors
                      (sdl2-ffi.functions:sdl-render-set-logical-size ren +window-width+ +window-height+))
                     (setf fullscreen-applied enabled)
                     t)
                   (maybe-apply-fullscreen ()
                     (let ((desired (not (null (game-state-fullscreen-enabled state)))))
                       (unless (eql desired fullscreen-applied)
                         (apply-fullscreen desired))))
                   (window->logical (x y)
                     (let ((max-x (coerce (1- +window-width+) 'double-float))
                           (max-y (coerce (1- +window-height+) 'double-float)))
                       (handler-case
                           (cffi:with-foreign-objects ((lx :float) (ly :float))
                             (sdl2-ffi.functions:sdl-render-window-to-logical ren x y lx ly)
                             (let ((fx (coerce (cffi:mem-ref lx :float) 'double-float))
                                   (fy (coerce (cffi:mem-ref ly :float) 'double-float)))
                               (values (truncate (clamp fx 0.0d0 max-x))
                                       (truncate (clamp fy 0.0d0 max-y)))))
                         (error ()
                           ;; Fallback: scale relative to current renderer output.
                           (multiple-value-bind (win-w win-h) (sdl2:get-window-size win)
                             (multiple-value-bind (out-w out-h) (sdl2:get-renderer-output-size ren)
                               (let* ((win-w (max 1 win-w))
                                      (win-h (max 1 win-h))
                                      (out-w (max 1 out-w))
                                      (out-h (max 1 out-h))
                                      (wx (coerce x 'double-float))
                                      (wy (coerce y 'double-float))
                                      (ox (* wx (/ (coerce out-w 'double-float)
                                                   (coerce win-w 'double-float))))
                                      (oy (* wy (/ (coerce out-h 'double-float)
                                                   (coerce win-h 'double-float))))
                                      (lx (/ (* ox (coerce +window-width+ 'double-float))
                                             (coerce out-w 'double-float)))
                                      (ly (/ (* oy (coerce +window-height+ 'double-float))
                                             (coerce out-h 'double-float))))
                                 (values (truncate (clamp lx 0.0d0 max-x))
                                         (truncate (clamp ly 0.0d0 max-y)))))))))))
	            (ensure-fonts-loaded)
	            (init-resource-caps! state)
	            (recompute-production! state)
	            (setf (game-state-screen state) :menu)
	            (setf (game-state-game-started-p state) nil)
	            (reset-timer)
	            (unwind-protect
	                (sdl2:with-event-loop (:method :poll)
	                  (:keydown (:keysym keysym)
	                    (handle-keydown state keysym))
	                  (:mousebuttondown (:x x :y y :button btn)
	                    (setf mouse-win-x x mouse-win-y y)
	                    (when (= btn 1) (setf clicked t)))
	                  (:mousemotion (:x x :y y)
	                    (setf mouse-win-x x mouse-win-y y))
	                  (:idle ()
	                    (let ((dt (compute-dt)))
	                      (setf (game-state-dt state) dt)
	                      (if (eq (game-state-screen state) :game)
	                          (tick-game state dt)
	                          (update-fps! state dt))
	                      (maybe-reload-fonts)
	                      (maybe-apply-fullscreen)
	                      (multiple-value-bind (mw-x mw-y buttons) (sdl2:mouse-state)
	                        (setf mouse-win-x mw-x
	                              mouse-win-y mw-y)
	                        (let* ((left-down (plusp (logand buttons 1)))
	                               (edge-click (and left-down (not prev-left-down)))
	                               (frame-click (or clicked edge-click)))
	                          (setf prev-left-down left-down)
	                          (multiple-value-bind (mx my) (window->logical mouse-win-x mouse-win-y)
		                            (ui-begin-frame :mouse-x mx :mouse-y my :clicked frame-click)
		                            (render-frame ren state font font-lg))))
	                      (setf clicked nil)
	                      (when (eq (game-state-screen state) :game)
	                        (maybe-autosave state))))
	                  (:quit ()
	                    (ignore-errors (save-options state))
	                    (when (game-state-game-started-p state)
	                      (save-game state)
	                      (setf (game-state-last-save-ut state) (get-universal-time)))
	                    t))
	              (when (> (sdl2-ttf:was-init) 0)
	                (clear-panel-backgrounds!)
	                (when font (sdl2-ttf:close-font font))
	                (when font-lg (sdl2-ttf:close-font font-lg))
	                (sdl2-ttf:quit))
	              (sdl2-image:quit))))))))

(defun main ()
  (run-game))
